# Generated by Django 3.2.4 on 2021-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knn_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id_history', models.IntegerField(primary_key=True, serialize=False)),
                ('hero_name', models.CharField(max_length=200)),
                ('hero_damage', models.IntegerField()),
                ('turret_damage', models.IntegerField()),
                ('damage_taken', models.IntegerField()),
                ('war_participation', models.IntegerField()),
                ('result', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.IntegerField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pengguna',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='id_user',
        ),
    ]
