# Generated by Django 3.2.4 on 2021-11-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knn_model', '0004_knn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Knn',
        ),
    ]
