# Generated by Django 3.2.4 on 2021-11-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knn_model', '0005_delete_knn'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='id_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='knn_model.user'),
            preserve_default=False,
        ),
    ]
