# Generated by Django 3.2.4 on 2022-02-02 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knn_model', '0007_auto_20211121_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id_statistic', models.AutoField(primary_key=True, serialize=False)),
                ('winrate', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
