# Generated by Django 3.2.4 on 2022-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knn_model', '0008_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='hero_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
